# MongoDB connection
spring.data.mongodb.uri=mongodb+srv://lavapperiyan2004_db_user:LsN6Myr0L0psZUQF@jaffnacar.vku9qkm.mongodb.net/jaffna_vehicle_spot?retryWrites=true&w=majority&appName=Jaffnacar

# JWT Properties
jaffnavicle.app.jwtSecret=secret1234567890secret1234567890secret1234567890
jaffnavicle.app.jwtExpirationMs=2592000000

# Server Port
server.port=8080

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.cnl.global.jaffnavicle=DEBUG
